[package]
name = "orion-template"
version = "1.0.0"
edition = "2021"

[dependencies]
orion-core = { path = "../orion-core" }

[build-dependencies]
orion-core = { path = "../orion-core" }

# [profile.release]
# lto = true
# codegen-units = 1
# panic = "abort"