[package]
name = "network-benchmark-client"
version = "1.0.0"
edition = "2021"

[dependencies]
capybara = { path = "../../../../capybara", features = [ "network" ] }
network-benchmark-base = { path = "../base" }

[build-dependencies]
anyhow = { version = "1.0.79" }
