[workspace]
resolver = "2"
members = [
    "capybara",

    "examples/benchmark",
    "examples/ldtk",
    "examples/light",
    "examples/particles",
    "examples/physics",
    "examples/template",
    "examples/ui",
    
    "examples/network/base",
    "examples/network/client",
    "examples/network/server",
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"