[workspace]
members = [
    "orion-core",
    "orion-template",

    "examples/benchmark",
    "examples/particles",
    "examples/physics",
    "examples/ui",
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"