[workspace]
resolver = "2"
members = [
    "capybara",
    "template",

    "examples/benchmark",
    "examples/lighting",
    "examples/particles",
    "examples/physics",
    "examples/ui",
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"