(function() {var implementors = {
"benchmark":[["impl Scene&lt;<a class=\"struct\" href=\"benchmark/struct.GlobalData.html\" title=\"struct benchmark::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"benchmark/struct.MainScene.html\" title=\"struct benchmark::MainScene\">MainScene</a>"]],
"ldtk":[["impl Scene&lt;<a class=\"struct\" href=\"ldtk/struct.GlobalData.html\" title=\"struct ldtk::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"ldtk/struct.MainScene.html\" title=\"struct ldtk::MainScene\">MainScene</a>"]],
"light":[["impl Scene&lt;<a class=\"struct\" href=\"light/struct.GlobalData.html\" title=\"struct light::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"light/struct.MainScene.html\" title=\"struct light::MainScene\">MainScene</a>"]],
"particles":[["impl Scene&lt;<a class=\"struct\" href=\"particles/struct.GlobalData.html\" title=\"struct particles::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"particles/struct.MainScene.html\" title=\"struct particles::MainScene\">MainScene</a>"]],
"physics":[["impl Scene&lt;<a class=\"struct\" href=\"physics/struct.GlobalData.html\" title=\"struct physics::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"physics/struct.MainScene.html\" title=\"struct physics::MainScene\">MainScene</a>"]],
"powder":[["impl Scene&lt;<a class=\"struct\" href=\"powder/struct.GlobalData.html\" title=\"struct powder::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"powder/struct.MainScene.html\" title=\"struct powder::MainScene\">MainScene</a>"]],
"simple_client":[["impl Scene&lt;<a class=\"struct\" href=\"simple_client/struct.GlobalData.html\" title=\"struct simple_client::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"simple_client/struct.MainScene.html\" title=\"struct simple_client::MainScene\">MainScene</a>"]],
"snake_client":[["impl Scene&lt;<a class=\"struct\" href=\"snake_client/scenes/struct.GlobalData.html\" title=\"struct snake_client::scenes::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"snake_client/scenes/game/struct.GameScene.html\" title=\"struct snake_client::scenes::game::GameScene\">GameScene</a>"],["impl Scene&lt;<a class=\"struct\" href=\"snake_client/scenes/struct.GlobalData.html\" title=\"struct snake_client::scenes::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"snake_client/scenes/loading/struct.LoadingScene.html\" title=\"struct snake_client::scenes::loading::LoadingScene\">LoadingScene</a>"],["impl Scene&lt;<a class=\"struct\" href=\"snake_client/scenes/struct.GlobalData.html\" title=\"struct snake_client::scenes::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"snake_client/scenes/boot/struct.BootScene.html\" title=\"struct snake_client::scenes::boot::BootScene\">BootScene</a>"],["impl Scene&lt;<a class=\"struct\" href=\"snake_client/scenes/struct.GlobalData.html\" title=\"struct snake_client::scenes::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"snake_client/scenes/menu/struct.MenuScene.html\" title=\"struct snake_client::scenes::menu::MenuScene\">MenuScene</a>"]],
"template":[["impl Scene&lt;<a class=\"struct\" href=\"template/scenes/struct.GlobalData.html\" title=\"struct template::scenes::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"template/scenes/boot/struct.BootScene.html\" title=\"struct template::scenes::boot::BootScene\">BootScene</a>"],["impl Scene&lt;<a class=\"struct\" href=\"template/scenes/struct.GlobalData.html\" title=\"struct template::scenes::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"template/scenes/game/struct.GameScene.html\" title=\"struct template::scenes::game::GameScene\">GameScene</a>"],["impl Scene&lt;<a class=\"struct\" href=\"template/scenes/struct.GlobalData.html\" title=\"struct template::scenes::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"template/scenes/loading/struct.LoadingScene.html\" title=\"struct template::scenes::loading::LoadingScene\">LoadingScene</a>"],["impl Scene&lt;<a class=\"struct\" href=\"template/scenes/struct.GlobalData.html\" title=\"struct template::scenes::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"template/scenes/menu/struct.MenuScene.html\" title=\"struct template::scenes::menu::MenuScene\">MenuScene</a>"]],
"ui":[["impl Scene&lt;<a class=\"struct\" href=\"ui/struct.GlobalData.html\" title=\"struct ui::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"ui/struct.MainScene.html\" title=\"struct ui::MainScene\">MainScene</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()