(function() {var implementors = {
"benchmark":[["impl <a class=\"trait\" href=\"capybara/scene/trait.Scene.html\" title=\"trait capybara::scene::Scene\">Scene</a>&lt;<a class=\"struct\" href=\"benchmark/struct.GlobalData.html\" title=\"struct benchmark::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"benchmark/struct.MainScene.html\" title=\"struct benchmark::MainScene\">MainScene</a>"]],
"ldtk":[["impl <a class=\"trait\" href=\"capybara/scene/trait.Scene.html\" title=\"trait capybara::scene::Scene\">Scene</a>&lt;<a class=\"struct\" href=\"ldtk/struct.GlobalData.html\" title=\"struct ldtk::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"ldtk/struct.MainScene.html\" title=\"struct ldtk::MainScene\">MainScene</a>"]],
"light":[["impl <a class=\"trait\" href=\"capybara/scene/trait.Scene.html\" title=\"trait capybara::scene::Scene\">Scene</a>&lt;<a class=\"struct\" href=\"light/struct.GlobalData.html\" title=\"struct light::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"light/struct.MainScene.html\" title=\"struct light::MainScene\">MainScene</a>"]],
"network_client":[["impl Scene&lt;<a class=\"struct\" href=\"network_client/struct.GlobalData.html\" title=\"struct network_client::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"network_client/struct.MainScene.html\" title=\"struct network_client::MainScene\">MainScene</a>"]],
"particles":[["impl Scene&lt;<a class=\"struct\" href=\"particles/struct.GlobalData.html\" title=\"struct particles::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"particles/struct.MainScene.html\" title=\"struct particles::MainScene\">MainScene</a>"]],
"physics":[["impl <a class=\"trait\" href=\"capybara/scene/trait.Scene.html\" title=\"trait capybara::scene::Scene\">Scene</a>&lt;<a class=\"struct\" href=\"physics/struct.GlobalData.html\" title=\"struct physics::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"physics/struct.MainScene.html\" title=\"struct physics::MainScene\">MainScene</a>"]],
"template":[["impl <a class=\"trait\" href=\"capybara/scene/trait.Scene.html\" title=\"trait capybara::scene::Scene\">Scene</a>&lt;<a class=\"struct\" href=\"template/scenes/struct.GlobalData.html\" title=\"struct template::scenes::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"template/scenes/boot/struct.BootScene.html\" title=\"struct template::scenes::boot::BootScene\">BootScene</a>"],["impl <a class=\"trait\" href=\"capybara/scene/trait.Scene.html\" title=\"trait capybara::scene::Scene\">Scene</a>&lt;<a class=\"struct\" href=\"template/scenes/struct.GlobalData.html\" title=\"struct template::scenes::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"template/scenes/menu/struct.MenuScene.html\" title=\"struct template::scenes::menu::MenuScene\">MenuScene</a>"],["impl <a class=\"trait\" href=\"capybara/scene/trait.Scene.html\" title=\"trait capybara::scene::Scene\">Scene</a>&lt;<a class=\"struct\" href=\"template/scenes/struct.GlobalData.html\" title=\"struct template::scenes::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"template/scenes/loading/struct.LoadingScene.html\" title=\"struct template::scenes::loading::LoadingScene\">LoadingScene</a>"],["impl <a class=\"trait\" href=\"capybara/scene/trait.Scene.html\" title=\"trait capybara::scene::Scene\">Scene</a>&lt;<a class=\"struct\" href=\"template/scenes/struct.GlobalData.html\" title=\"struct template::scenes::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"template/scenes/game/struct.GameScene.html\" title=\"struct template::scenes::game::GameScene\">GameScene</a>"]],
"ui":[["impl <a class=\"trait\" href=\"capybara/scene/trait.Scene.html\" title=\"trait capybara::scene::Scene\">Scene</a>&lt;<a class=\"struct\" href=\"ui/struct.GlobalData.html\" title=\"struct ui::GlobalData\">GlobalData</a>&gt; for <a class=\"struct\" href=\"ui/struct.MainScene.html\" title=\"struct ui::MainScene\">MainScene</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()