[package]
name = "powder"
version = "1.0.0"
edition = "2021"

[dependencies]
capybara = { path = "../../capybara", features = [ "physics", "powder" ] }

[build-dependencies]
anyhow = { version = "1.0.79" }
