[package]
name = "ui"
version = "1.0.0"
edition = "2021"

[dependencies]
orion-core = { path = "../../orion-core" }
fastrand = { version = "2.0.0" }

[build-dependencies]
orion-core = { path = "../../orion-core" }