[package]
name = "capybara-template"
version = "1.0.0"
edition = "2021"

[dependencies]
capybara-core = { path = "../capybara-core" }

[build-dependencies]
cfg_aliases = { version = "0.1.1" }

# [profile.release]
# lto = true
# codegen-units = 1
# panic = "abort"