[package]
name = "orion-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.70" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [ "winuser", "libloaderapi", "errhandlingapi" ] }

[target.'cfg(target_arch = "wasm32")'.dependencies]