[package]
name = "network-client"
version = "1.0.0"
edition = "2021"

[dependencies]
network-base = { path = "../base" }
capybara = { path = "../../../capybara", features = [ "network" ] }

[build-dependencies]
anyhow = { version = "1.0.75" }
