[package]
name = "simple-client"
version = "1.0.0"
edition = "2021"

[dependencies]
capybara = { path = "../../../../capybara", features = [ "network" ] }
simple-base = { path = "../base" }

[build-dependencies]
anyhow = { version = "1.0.79" }
